import { Product } from "@/types";

export const productos: Product[] = [
  {
    id: 1,
    nombre: "Zapatillas Ultraboost 5x",
    descripcion:
      "Disfruta de comodidad y rendimiento superior con las Zapatillas Ultraboost 5x. Su entresuela Boost proporciona una amortiguación reactiva, mientras que la parte superior de tejido Primeknit se ajusta perfectamente al pie. La suela de goma Continental™ garantiza un excelente agarre en cualquier superficie. Ideales tanto para correr como para el uso diario, las Ultraboost 5x combinan estilo, ligereza y soporte en cada paso.",
    categoria: "Urbano",
    seccion: "hombre",
    precio: 180.0,
    valuacion: 3,
    marca: "adidas",
    tallas: [38, 39, 40, 41, 42, 43, 44],
    colors: ["blanco", "azul", "verde"],
    peso: 200,
    paqueteDimensiones: {
      ancho: 15.14,
      largo: 13.08,
      profundidad: 22.99,
    },
    garantia: "1 semana de garantia",
    envio: "Envios en 3-5 días hábiles",
    comentarios: [
      {
        valuacion: 3,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
      {
        valuacion: 4,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Lucas Gordon",
        correo: "lucas.gordon@x.dummyjson.com",
      },
      {
        valuacion: 5,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
    ],
    politicaDevolucion: "No politicas de devolucion",
    images: ["/ultraboost-4.webp", "/ultraboost-5.webp", "/ultraboost-6.webp"],
    thumbnail: "/producto1.webp",
  },
  {
    id: 2,
    nombre: "Zapatillas Suede Classic unisex",
    descripcion:
      "Disfruta de comodidad y rendimiento superior con las Zapatillas Ultraboost 5x. Su entresuela Boost proporciona una amortiguación reactiva, mientras que la parte superior de tejido Primeknit se ajusta perfectamente al pie. La suela de goma Continental™ garantiza un excelente agarre en cualquier superficie. Ideales tanto para correr como para el uso diario, las Ultraboost 5x combinan estilo, ligereza y soporte en cada paso.",
    categoria: "Urbano",
    seccion: "hombre",
    precio: 125.0,
    valuacion: 2.56,
    marca: "puma",
    tallas: [38, 39, 40],
    colors: ["blanco", "azul", "rojo"],
    peso: 200,
    paqueteDimensiones: {
      ancho: 15.14,
      largo: 13.08,
      profundidad: 22.99,
    },
    garantia: "1 semana de garantia",
    envio: "Envios en 3-5 días hábiles",
    comentarios: [
      {
        valuacion: 4,
        comentario:
          "Excelente calidad y muy cómodas. El diseño clásico combina con todo.",
        titulo: "¡Perfectas para cualquier ocasión!",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
      {
        valuacion: 3,
        comentario:
          "Me encantó el color y el ajuste. Son ideales para uso diario.",
        titulo: "Muy recomendadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Lucas Gordon",
        correo: "lucas.gordon@x.dummyjson.com",
      },
      {
        valuacion: 5,
        comentario:
          "Ligeras y con materiales de primera. Volvería a comprarlas sin dudar.",
        titulo: "Gran compra",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
      {
        valuacion: 3,
        comentario:
          "Me encantó el color y el ajuste. Son ideales para uso diario.",
        titulo: "Muy recomendadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Lucas Gordon",
        correo: "lucas.gordon@x.dummyjson.com",
      },
      {
        valuacion: 5,
        comentario:
          "Ligeras y con materiales de primera. Volvería a comprarlas sin dudar.",
        titulo: "Gran compra",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
    ],
    politicaDevolucion: "No politicas de devolucion",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto2.webp",
  },
  {
    id: 3,
    nombre: "Zapatillas Response Runner",
    descripcion:
      "Disfruta de comodidad y rendimiento superior con las Zapatillas Ultraboost 5x. Su entresuela Boost proporciona una amortiguación reactiva, mientras que la parte superior de tejido Primeknit se ajusta perfectamente al pie. La suela de goma Continental™ garantiza un excelente agarre en cualquier superficie. Ideales tanto para correr como para el uso diario, las Ultraboost 5x combinan estilo, ligereza y soporte en cada paso.",
    categoria: "Deporte",
    seccion: "hombre",
    precio: 150.0,
    valuacion: 2.56,
    marca: "adidas",
    tallas: [38, 39, 40, 41, 42],
    colors: ["azul"],
    peso: 200,
    paqueteDimensiones: {
      ancho: 15.14,
      largo: 13.08,
      profundidad: 22.99,
    },
    garantia: "1 semana de garantia",
    envio: "Envios en 3-5 días hábiles",
    comentarios: [
      {
        valuacion: 3,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
      {
        valuacion: 4,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Lucas Gordon",
        correo: "lucas.gordon@x.dummyjson.com",
      },
      {
        valuacion: 5,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
    ],
    politicaDevolucion: "No politicas de devolucion",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto3.webp",
  },
  {
    id: 4,
    nombre: "Nike Air Force 1 '07",
    descripcion:
      "Disfruta de comodidad y rendimiento superior con las Zapatillas Ultraboost 5x. Su entresuela Boost proporciona una amortiguación reactiva, mientras que la parte superior de tejido Primeknit se ajusta perfectamente al pie. La suela de goma Continental™ garantiza un excelente agarre en cualquier superficie. Ideales tanto para correr como para el uso diario, las Ultraboost 5x combinan estilo, ligereza y soporte en cada paso.",
    categoria: "casual",
    seccion: "hombre",
    precio: 125.0,
    valuacion: 2.56,
    marca: "nike",
    tallas: [40, 41, 42],
    colors: ["gris", "blanco"],
    peso: 200,
    paqueteDimensiones: {
      ancho: 15.14,
      largo: 13.08,
      profundidad: 22.99,
    },
    garantia: "1 semana de garantia",
    envio: "Envios en 3-5 días hábiles",
    comentarios: [
      {
        valuacion: 3,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
      {
        valuacion: 4,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Lucas Gordon",
        correo: "lucas.gordon@x.dummyjson.com",
      },
      {
        valuacion: 5,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
    ],
    politicaDevolucion: "No politicas de devolucion",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto4.webp",
  },
  {
    id: 5,
    nombre: "Adidas Ultraboost 5x",
    descripcion:
      "Zapatillas diseñadas para ofrecer máxima amortiguación y retorno de energía, ideales para corredores que buscan comodidad y rendimiento.",
    categoria: "running",
    seccion: "unisex",
    precio: 180.0,
    valuacion: 4.8,
    marca: "adidas",
    tallas: [38, 39, 40, 41, 42, 43],
    colors: ["blanco", "gris"],
    peso: 250,
    paqueteDimensiones: {
      ancho: 16.0,
      largo: 30.0,
      profundidad: 12.0,
    },
    garantia: "6 meses de garantía",
    envio: "Envíos en 2-4 días hábiles",
    comentarios: [
      {
        valuacion: 5,
        comentario: "Muy cómodas y perfectas para correr largas distancias.",
        titulo: "Comodidad insuperable",
        fecha: "2025-05-15T10:20:00.000Z",
        nombre: "Ana López",
        correo: "ana.lopez@email.com",
      },
      {
        valuacion: 4,
        comentario: "Buen diseño y buen soporte, aunque un poco caras.",
        titulo: "Excelente calidad",
        fecha: "2025-05-10T14:30:00.000Z",
        nombre: "Jorge Martínez",
        correo: "jorge.martinez@email.com",
      },
    ],
    politicaDevolucion: "Devolución en 30 días con etiqueta prepagada",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto5.webp",
  },
  {
    id: 6,
    nombre: "Puma Suede Classic",
    descripcion:
      "Clásicas zapatillas de gamuza con estilo atemporal, perfectas para cualquier ocasión casual.",
    categoria: "casual",
    seccion: "unisex",
    precio: 90.0,
    valuacion: 4.2,
    marca: "puma",
    tallas: [37, 38, 39, 40, 41],
    colors: ["rojo", "blanco"],
    peso: 220,
    paqueteDimensiones: {
      ancho: 15.0,
      largo: 28.0,
      profundidad: 11.0,
    },
    garantia: "3 meses de garantía",
    envio: "Envíos en 3-5 días hábiles",
    comentarios: [
      {
        valuacion: 5,
        comentario: "Clásicas y con estilo, perfectas para cualquier outfit.",
        titulo: "Estilo atemporal",
        fecha: "2025-04-20T09:00:00.000Z",
        nombre: "Laura Sánchez",
        correo: "laura.sanchez@email.com",
      },
      {
        valuacion: 3,
        comentario: "Cómodas pero el color se desgastó rápido.",
        titulo: "Buena pero con detalles",
        fecha: "2025-04-25T11:15:00.000Z",
        nombre: "Miguel Torres",
        correo: "miguel.torres@email.com",
      },
    ],
    politicaDevolucion: "Devolución en 15 días sin costo",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto6.webp",
  },
  {
    id: 7,
    nombre: "Reebok Classic Leather",
    descripcion:
      "Zapatillas de cuero clásico con diseño elegante y comodidad para el uso diario.",
    categoria: "casual",
    seccion: "mujer",
    precio: 110.0,
    valuacion: 4.5,
    marca: "reebok",
    tallas: [36, 37, 38, 39, 40],
    colors: ["blanco", "rosa"],
    peso: 230,
    paqueteDimensiones: {
      ancho: 14.5,
      largo: 27.5,
      profundidad: 10.5,
    },
    garantia: "6 meses de garantía",
    envio: "Envíos en 2-4 días hábiles",
    comentarios: [
      {
        valuacion: 5,
        comentario: "Muy cómodas y con un diseño elegante.",
        titulo: "Perfectas para el día a día",
        fecha: "2025-05-05T13:45:00.000Z",
        nombre: "Sofía Ruiz",
        correo: "sofia.ruiz@email.com",
      },
      {
        valuacion: 4,
        comentario: "Buen soporte pero un poco pesadas para correr.",
        titulo: "Cómodas pero pesadas",
        fecha: "2025-05-08T08:30:00.000Z",
        nombre: "Carla Méndez",
        correo: "carla.mendez@email.com",
      },
    ],
    politicaDevolucion: "Devolución en 30 días con etiqueta prepagada",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto7.webp",
  },
  {
    id: 8,
    nombre: "Nike Air Force 1 '07",
    descripcion:
      "Zapatillas icónicas con diseño clásico y versatilidad para cualquier ocasión casual.",
    categoria: "casual",
    seccion: "hombre",
    precio: 125.0,
    valuacion: 2.56,
    marca: "nike",
    tallas: [40, 41, 42],
    colors: ["blanco"],
    peso: 200,
    paqueteDimensiones: {
      ancho: 15.14,
      largo: 13.08,
      profundidad: 22.99,
    },
    garantia: "1 semana de garantía",
    envio: "Envíos en 3-5 días hábiles",
    comentarios: [
      {
        valuacion: 3,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
      {
        valuacion: 4,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Lucas Gordon",
        correo: "lucas.gordon@x.dummyjson.com",
      },
      {
        valuacion: 5,
        comentario:
          "Son bonitas pero me parecieron un poco estrechas para mi pie.",
        titulo: "Buen diseño, pero algo ajustadas",
        fecha: "2025-04-30T09:41:02.053Z",
        nombre: "Eleanor Collins",
        correo: "eleanor.collins@x.dummyjson.com",
      },
    ],
    politicaDevolucion: "No políticas de devolución",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto8.webp",
  },
  {
    id: 9,
    nombre: "New Balance 574",
    descripcion:
      "Zapatillas resistentes y cómodas, ideales para entrenamientos diarios y uso casual.",
    categoria: "running",
    seccion: "hombre",
    precio: 100.0,
    valuacion: 4.0,
    marca: "new balance",
    tallas: [39, 40, 41, 42],
    colors: ["gris", "azul"],
    peso: 240,
    paqueteDimensiones: {
      ancho: 15.5,
      largo: 29.0,
      profundidad: 11.5,
    },
    garantia: "3 meses de garantía",
    envio: "Envíos en 2-4 días hábiles",
    comentarios: [
      {
        valuacion: 4,
        comentario: "Cómodas y resistentes, perfectas para entrenar.",
        titulo: "Muy buenas para correr",
        fecha: "2025-05-12T12:00:00.000Z",
        nombre: "Diego Pérez",
        correo: "diego.perez@email.com",
      },
      {
        valuacion: 3,
        comentario: "El diseño es bueno pero la talla me quedó un poco grande.",
        titulo: "Talla un poco grande",
        fecha: "2025-05-14T09:30:00.000Z",
        nombre: "Mariana Gómez",
        correo: "mariana.gomez@email.com",
      },
    ],
    politicaDevolucion: "Devolución en 15 días sin costo",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto9.webp",
  },
  {
    id: 10,
    nombre: "Asics Gel-Kayano 28",
    descripcion:
      "Zapatillas con excelente soporte y amortiguación, perfectas para corredoras que buscan rendimiento y confort.",
    categoria: "running",
    seccion: "mujer",
    precio: 160.0,
    valuacion: 4.7,
    marca: "asics",
    tallas: [37, 38, 39, 40],
    colors: ["blanco", "rosa"],
    peso: 260,
    paqueteDimensiones: {
      ancho: 16.0,
      largo: 30.0,
      profundidad: 12.0,
    },
    garantia: "6 meses de garantía",
    envio: "Envíos en 2-4 días hábiles",
    comentarios: [
      {
        valuacion: 5,
        comentario: "Excelente soporte y amortiguación para largas carreras.",
        titulo: "Ideal para runners",
        fecha: "2025-05-18T15:20:00.000Z",
        nombre: "Valeria Castillo",
        correo: "valeria.castillo@email.com",
      },
      {
        valuacion: 4,
        comentario: "Cómodas pero un poco pesadas para uso diario.",
        titulo: "Buen rendimiento",
        fecha: "2025-05-20T10:10:00.000Z",
        nombre: "Natalia Ríos",
        correo: "natalia.rios@email.com",
      },
    ],
    politicaDevolucion: "Devolución en 30 días con etiqueta prepagada",
    images: ["/ultraboost-1.webp", "/ultraboost-2.webp", "/ultraboost-3.webp"],
    thumbnail: "/producto10.webp",
  },
];

export const categorias = [
  {
    id: 1,
    nombre: "Urbano",
    descripcion:
      "Zapatillas diseñadas para correr y entrenamiento cardiovascular.",
    imagen: "/categorias/running.png",
  },
  {
    id: 2,
    nombre: "Casual",
    descripcion: "Zapatillas para uso diario y estilo informal.",
    imagen: "/categorias/casual.png",
  },
  {
    id: 3,
    nombre: "Deporte",
    descripcion:
      "Zapatillas con soporte y amortiguación para jugar baloncesto.",
    imagen: "/categorias/basketball.png",
  },
  {
    id: 4,
    nombre: "Senderismo",
    descripcion:
      "Zapatillas para correr en terrenos irregulares y al aire libre.",
    imagen: "/categorias/trail.png",
  },
  {
    id: 5,
    nombre: "Gym",
    descripcion:
      "Zapatillas para entrenamiento en gimnasio y actividades multidisciplinarias.",
    imagen: "/categorias/training.png",
  },
];

// export const redes = [
//   {
//     nombre: "Facebook",
//     url: "#",
//     icono: "/facebook.svg",
//   },
//   {
//     nombre: "Twitter",
//     url: "#",
//     icono: "/twitter.svg",
//   },
//   {
//     nombre: "Instagram",
//     url: "#",
//     icono: "/instagram.svg",
//   },
//   {
//     nombre: "Tiktok",
//     url: "#",
//     icono: "/tiktok.svg",
//   },
// ];
